openapi: 3.0.1
info:
  title: dem-elevation-extractor
  description: map colonies service for extracting elevations from DTM/DSM geotiffs
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

paths:
  /heights:
    get:
      operationId: getHeights
      tags:
        - heights
      summary: gets the heights
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/heights'
    post:
      operationId: getHeightsList
      tags:
        - heights
      summary: get the heights
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/heights'
components:
  schemas:
    error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    heights:
      type: object
      required:
        - dem
      properties:
        dem:
          type: number
          format: int64
